### ISSUE TITLE
Éditions 

### ISSUE THREAD

**Issue by glingo** [glingo/afpa-librairie#2]
Attention les rubriques le thème etc sont associés à l'ouvrage et non à l'édition

**Comment by Swaan00** [comment]
Oui je sais hier soir j'ai commencé à changer ça mais j'ai pas encore
commit ! Je m'en occupe.

**Comment by glingo** [comment]
No problemo c'était pour ne pas partir dans le faux ;)

**Comment by Swaan00** [comment]
Tkt paupiette ! Je gère !:D (ou pas.... XD)
