### ISSUE TITLE
Lili it works

### ISSUE THREAD

**Issue by glingo** [glingo/afpa-librairie#3]
Marine, je viens de commit la création / édition de l'ouvrage. 

Si tu veux voir comment j'ai fais pour les multiples etc.

**Comment by Swaan00** [comment]
Ok ! je regarde !

2016-09-16 16:49 GMT+02:00 glingo notifications@github.com:

**Comment by Swaan00** [comment]
quesiton : est ce que tu as sync? je ne vois pas les modifications ici

2016-09-16 16:55 GMT+02:00 Marÿn Oo marineg0108@gmail.com:

**Comment by Swaan00** [comment]
Oublie le dernier mail ! c'est bon ! C'est cool !!!
GG

2016-09-16 16:58 GMT+02:00 Marÿn Oo marineg0108@gmail.com:

**Comment by glingo** [comment]
![](http://i.imgur.com/v0Bri2H.jpg)

Oui j'ai push
